trydjango19/posts/urls.py
from django.conf.urls import url
from .views import (posts_home,
                    post_create,
                    post_delete,
                    post_detail,
                    post_list,
                    post_update
                    )

# Write your URL patterns here.
urlpatterns = [
    url(r'^$',  posts_home, name="home"),
    url(r'^create', post_create, name="post-create"),
    url(r'^delete/(?P<id>\d+)/$', post_delete, name="post-delete"),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="post-detail"),
    url(r'^list', post_list, name="post-list"),
    url(r'^(?P<id>\d+)/edit/$', post_update, name="post-update"),
]

trydjango19/trydjango19/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static

import posts.urls as post_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include(post_urls, namespace='posts'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trydjango19/posts/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.db.models.signals import pre_save
from django.contrib.contenttypes.models import ContentType

from markdown_deux import markdown

from comments.models import Comment

# Create your models here.

# Defines where the File will be uploaded.


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, default=1)
    title = models.CharField(max_length=120)
    draft = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    image = models.ImageField(
        upload_to=upload_location, null=True, blank=True, height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={
            "slug": self.slug
        })
        # return f"/posts/{self.id}/"

    class Meta:
        ordering = ["-timestamp", "-updated"]

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    exists = qs.exists()
    if exists:
        new_slug = f"{slug}-{qs.first().id}"
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_signal_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_signal_receiver, sender=Post)

trydjango19/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

# Create your forms here.


# Form for creating Post.
class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish"
        ]

trydjango19/posts/views.py
from django.db.models import Q
from django.utils import timezone
from urllib.parse import quote_plus
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.contrib.contenttypes.models import ContentType

from .models import Post
from .forms import PostForm
from comments.forms import CommentForm
from comments.models import Comment, CommentManager

# Create your views here.


def posts_home(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()

    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    # Search Query.
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)
        ).distinct()

    # Pagination
    paginator = Paginator(queryset_list, 2)
    page_request_var = "posts"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an Integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "page_request_var": page_request_var,
        "title": "Home",
        "today": today
    }
    return render(request, "index.html", context)


def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        print(form.cleaned_data.get('title'))
        instance.save()
        messages.success(request, "Post successfully Created.")
        return HttpResponseRedirect(instance.get_absolute_url())
    # if request.method == "POST":
    #     # Can be done like this
    #     # title = request.POST.get('title')
    #     # Post.objects.create(title=title)

    context = {
        "form": form,
        "title": "Create Post"
    }
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    # instance = Post.objects.get(slug=1)
    instance = get_object_or_404(Post, slug=slug)

    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    share_string = quote_plus(instance.content)

    intitial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }
    comment_form = CommentForm(request.POST or None, initial=intitial_data)
    if comment_form.is_valid():
        c_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        content_data = comment_form.cleaned_data.get('content')
        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=obj_id,
            content=content_data
        )

    comments = instance.comments

    context = {
        "instance": instance,
        "title": "Detail",
        "share_string": share_string,
        "comment_form": comment_form,
        "comments": comments,
    }

    return render(request, "post_detail.html", context)


def post_list(request):
    queryset_list = Post.objects.active()

    # Pagination
    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an Integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset_list,
    }

    return render(request, "post_list.html", context)


def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)

    form = PostForm(request.POST or None,
                    request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        print(form.cleaned_data.get('title'))
        messages.success(request, "Post successfully Updated.")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "instance": instance,
        "title": "Update",
        "form": form,
    }

    return render(request, "post_update_form.html", context)


def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)

    form = PostForm(request.POST or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.delete()
        messages.success(request, "Post successfully deleted.")
        return redirect('posts:post-list')

trydjango19/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CDN -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!-- Font Awesome CDN -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Local CSS -->
    {% load staticfiles %}
    <link rel="stylesheet" href=" {% static "css/base.css" %} ">

    <title>
        {% if  title  %}
            Blog - {{ title }}
        {% else %} 
            Blog
        {% endif %}
    </title>
</head>
<body>
    <!-- Facebook Comments Plugin SDK -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>

    <!-- Facebook Like and Share btn Plugin -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>

    <!-- Pinterest Social handle -->
    <script async defer src="https://assets.pinterest.com/js/pinit.js"></script>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="{% url 'posts:home' %}" class="btn btn-success navbar-btn">Home</a>
                <a href="{% url 'posts:post-create' %}" class="btn btn-primary navbar-btn">Create Post</a>
            </div>
        </div>
    </nav>
    {% include "messages_display.html" %}

    <div class="container">
        {% block bodyBlock %}
        {% endblock bodyBlock %}
    {% block head_extra %}{% endblock %}
    </div>



<!-- JQuery CDN -->
<script
  src="https://code.jquery.com/jquery-1.12.2.min.js"
  integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="
  crossorigin="anonymous"></script>

<!-- Boostrap JS -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!-- Markdown JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>

<!-- Local JS -->
{% load static %}
<script type='text/javascript'>


// For image responsiveness.
$(document).ready(function() {
  $(".post-detail-item img").each(function() {
    $(this).addClass("img-responsive");
  });

    // For Post Preview.
    var titleItem = $('#id_title')
    $("#preview-title").text(marked(titleItem.val()))

    function setTitle(value) {
        $('#preview-title').text(value);
    }

    setTitle(titleItem.val())

    titleInput.keyup(function() {
        var newContent = $(this).val()
        setTitle(newContent)
    })


    var contentInput = $('#id_content');
    $("#preview-content").html(contentInput);

    function setContent(value) {
        var markedContent = marked(value);
        $("#preview-content").html(markedContent);
        $('#preview-content img').each(function() {
            $(this).addClass('img-responsive');
        });
    };
    setContent(contentInput.val())

    contentInput.keyup(function() {
        var newContent = $(this).val()
        setContent(newContent)
    })

    

});



</script>

</body>
</html>

trydjango19/templates/posts/index.html
{% extends 'base.html' %}

{% block bodyBlock %}
<h1>Welcome to Blogging App</h1>

{% comment %} <h4><a href={% url 'posts:post-list' %}>Blogs</a></h4> {% endcomment %}
<div class="col-sm-8 col-sm-offset">
        <form class='row' action="" method="get">
            <div class="col-sm-6" >
                <div class="input-group">
                    <input class='form-control' type="text" name='q' placeholder='Search Posts' value="{{ request.GET.q }}" >
                    <span class="input-group-btn">
                        <button class="btn btn-default" type='submit'><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
        </form>
    <br>
    <div class="row">
        {% for obj in object_list %}
            <div class="col-sm-12">
                <div class="thumbnail">
                    {% if obj.image %}
                        <img src="{{ obj.image.url }}" class='img-responsive'>
                    {% endif %}
                <div class="caption post-detail-item">
                    {% if obj.draft %} <h3>Draft {% if obj.publish > today %} Future Post {% endif %} </h3> {% endif %}
                    <h3><a href= "{{ obj.get_absolute_url }}" >{{ obj.id }} - {{    obj.title }}</a>
                        <small>{{ obj.timestamp | timesince }}</small>
                    </h3>
                    <p >{{ obj.get_markdown }}</p>
                    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                    <p><a href="{% url 'posts:post-update' obj.id %}" class="btn btn-primary" role="button">Edit</a>
                    <p><a href="{% url 'posts:post-delete' obj.id %}" class="btn btn-danger" role="button">Delete</a>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
            {% endif %}
        </span>
    </div>

</div>

{% endblock bodyBlock %}

trydjango19/templates/posts/messages_display.html
{% if messages %}
        <div class="messages">
            <ul class="messages">
                {% for msg in messages %}
                    <li {% if msg.tags %} class="{{ msg }}" {% endif %} > {{ msg }} </li>
                {% endfor %}
            </ul>
        </div>
{% endif %}

trydjango19/templates/posts/post_detail.html
{% extends 'base.html' %}

{% load urlify %}
{% load crispy_forms_tags %}

{% block bodyBlock %}


<div class="col-sm-8 col-sm-offset-3">
    {% if instance.image %}
        <img src="{{ instance.image.url }}" class='img-responsive'>
    {% endif %}
    <h1>{{ instance.title }} {% if instance.draft %} <small>
        <span style='color:red;'>Draft</span>
    </small> {% endif %} <small>{{ instance.timestamp }}</small> </h1>
    <p>Author: {{ instance.user }}</p>
    </br>

    <div class="row">
        <div class="col-sm-12 post-detail-item content-markdown">
            <div>
                <p>{{ instance.get_markdown|truncatewords_html:10 }}</p>
            </div>
            <hr>
            <br>
            <!-- Facebook Like and Share button --> 
            <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-width="" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>

            <!-- Local Comments -->
            <div class="lead">
                <p>Comments</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ comment_form | crispy }}
                    <input type="submit" value="Post Comment" class='btn btn-default'>
                    <hr>
                </form>
                {% for comment in comments %}
                    <blockquote>
                        <p>{{ comment.content }}</p>
                        <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago </footer>
                    </blockquote>
                    <hr>
                {% endfor %}
            </div>

            <!-- Facebook Comments -->
            {% comment %} <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="100%" data-numposts="5"></div> {% endcomment %}
        </div>
    </div>

    <!-- Social Links Sharing. -->

    {% comment %} <p>
        <!-- Facebook -->
        <a href="https://www.facebook.com/sharer/sharer.php?u=http://{{ request.build_absolute_uri }}/">
        Share on Facebook
        </a>

        <!-- Twitter -->
        <a href="https://twitter.com/home?status={{ instance.content|urlify }}20{{ request.build_absolute_uri }}/">
        Share on Twitter
        </a>

        <!-- Google Plus -->
        <a href='https://plus.google.com/share?url=http://{{ request.build_absolute_uri }}'>Share on Google+</a>

        <!-- LinkedIn -->
        <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ instance.content|urlify }}&source={{ request.build_absolute_uri }}">
            Share on Linkedin
        </a>

        <!-- Reddit -->
        <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&{{ instance.content|urlify }}">Share on Reddit</a>

        <!-- Pinterest -->
        <a data-pin-do="buttonBookmark" href="{{ request.build_absolute_uri }}"><img src="{{ obj.image.url }}" /></a>
    </p> {% endcomment %}
</div>

{% endblock bodyBlock %}

trydjango19/templates/posts/post_form.html
{% extends 'base.html' %}

{% block head_extra %}

{{ form.media }}

{% endblock head_extra %}

{% block bodyBlock %}

<div class="col-sm-6">
    <h1>Preview</h1>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>

<div class="col-sm-6">
    <h1>Create an New Post</h1>

    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Create Post" class="btn btn-default">
    </form>
</div>


{% endblock bodyBlock %}

trydjango19/templates/posts/post_list.html
{% extends 'base.html' %}

{% block bodyBlock %}


{% for obj in object_list %}
    <div class="col-sm-6">
        <h1> <a href= {% comment %} {% url 'post-detail' id=obj.id %} {% endcomment %} {{ obj.get_absolute_url }} >{{ obj.id }} - {{    obj.title }}</a></h1>
        <p>{{ obj.content|linebreaks|truncatechars:120 }}</p></br>
        <p>{{ obj.timestamp }}</p></br>
        <p>{{ obj.updated }}</p></br>
    </div>
{% endfor %}

{% endblock bodyBlock %}

trydjango19/templates/posts/post_update_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head_extra %}

{{ form.media }}

{% endblock head_extra %}

{% block bodyBlock %}
<h1>Update Post</h1>

<div class="col-sm-6">
    <h1>Preview</h1>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>

<div class="col-sm-6">
    <h1>Update Post</h1>

    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        {{ form|crispy }}

        <input type="submit" value="Update Post" class="btn btn-default">
    </form>
</div>


{% endblock bodyBlock %}